### PR TITLE
Proposal : Augment resources typing

### PR DESCRIPTION
**Pull request by ymoriaud**
Hello ! 👋

I'm just discovering this library (thanks for the awesome work !) and I was struggling with callback typing. I saw the issue #45 and I wanted to share a potential solution.

**Disclaimer** : this PR is draft, the test is only done for the SCIMMY.Resources.User.ingress function.

Since the SCIMMY.Resources.User extends SCIMMY.Types.Resource and bring some override, I notice that typescript handle it better if we define a specific callback type for IngressHandler.

I also changed the return type of SCIMMY.Resources.declare by adding a dynamic type based on the declared type.

Here is an example that you can use in VSCode to test augmented typing.

```js
SCIMMY.Resources.declare(SCIMMY.Resources.User)
    .ingress((resource, data) => {
        /* Handler for creating or modifying user resources */
        console.log('Creating resource:', resource)
        console.log('Data', data)

        const user = {}
        return user
    })

```

Here is an example on how VSCode display the type for ingress.
image

### CODE REVIEW

**Comment by sleelin** [comment]
Hi @ymoriaud, apologies for the delay in addressing this PR!
Thanks for your contribution! It doesn't quite address the underlying issue and isn't a full solution (the other resource types have the same problem), so I can't merge this as-is.

The underlying issue is that the type definitions generated from the JSDoc annotations by the TypeScript compiler are functionally useless - when they don't just fall back to the "any" type, they often just outright get the type wrong.
I've been working on a new tool to manually generate the types, and have had much better results, including using the `@template` tag as you suggested to generate generic types.

I'm closing this for now as I have a more comprehensive solution on the way shortly!

**Comment by ymoriaud** [comment]
Hello @sleelin ! Thanks for your answer. Congrats for the new tool !
Feel free to ping me if you are looking for some help or testers.

Have a great day.

**Comment by sleelin** [comment]
Thanks @ymoriaud! I've just released v1.3.0 which should include a type definition file generated with the new tool, would you mind updating to this version and reporting back firstly on whether it actually produced functioning types, and secondly to see if it raises any other typing issues?

Thanks,
Sam

**Comment by ymoriaud** [comment]
Thanks @sleelin and congrats for the release ! I'm answering in the #45 to centralize everything. If you prefer for me to create a new issue, let me know. :)

**Pull request closed without merging**
